### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by zhangxue123** [JunshengFu/vehicle-detection#5]
there is a problem when run the code, please help me, thank you very much.

Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1139, in _do_call
    return fn(*args)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1121, in _run_fn
    status, run_metadata)
  File "D:\Anaconda3\lib\contextlib.py", line 89, in __exit__
    next(self.gen)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for weights/YOLO_small.ckpt
	 [[Node: save/RestoreV2_2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_2/tensor_names, save/RestoreV2_2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/vehicle-detection-master/main.py", line 4, in <module>
    from yolo_pipeline import *
  File "C:\Users\Administrator\PycharmProjects\vehicle-detection-master\yolo_pipeline.py", line 211, in <module>
    yolo = yolo_tf()
  File "C:\Users\Administrator\PycharmProjects\vehicle-detection-master\yolo_pipeline.py", line 25, in __init__
    self.build_networks()
  File "C:\Users\Administrator\PycharmProjects\vehicle-detection-master\yolo_pipeline.py", line 66, in build_networks
    self.saver.restore(self.sess, self.weights_file)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 789, in run
    run_metadata_ptr)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for weights/YOLO_small.ckpt
	 [[Node: save/RestoreV2_2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_2/tensor_names, save/RestoreV2_2/shape_and_slices)]]

Caused by op 'save/RestoreV2_2', defined at:
  File "C:/Users/Administrator/PycharmProjects/vehicle-detection-master/main.py", line 4, in <module>
    from yolo_pipeline import *
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\Administrator\PycharmProjects\vehicle-detection-master\yolo_pipeline.py", line 211, in <module>
    yolo = yolo_tf()
  File "C:\Users\Administrator\PycharmProjects\vehicle-detection-master\yolo_pipeline.py", line 25, in __init__
    self.build_networks()
  File "C:\Users\Administrator\PycharmProjects\vehicle-detection-master\yolo_pipeline.py", line 65, in build_networks
    self.saver = tf.train.Saver()
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1139, in __init__
    self.build()
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 691, in build
    restore_sequentially, reshape)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 640, in restore_v2
    dtypes=dtypes, name=name)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for weights/YOLO_small.ckpt
	 [[Node: save/RestoreV2_2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_2/tensor_names, save/RestoreV2_2/shape_and_slices)]]

**Comment by JunshengFu** [comment]
Hi @zhangxue123 
I only have tested my pipline in ubuntu 16.04 not in Windows yet. Since I don't have a windows pc for work, I might not able to help you to debug.

**Comment by zhangxue123** [comment]
@JunshengFu thank you very much.

**Comment by NicWayand** [comment]
@zhangxue123 Did you ever get this working on Windows?

**Comment by zhangxue123** [comment]
@NicWayand The code can run on Windows, and the error here is that the weight file YOLO_small.ckpt is not in the project.
